### ISSUE TITLE
 Lost sync with device Error

### ISSUE THREAD

**Issue by romainreignier** [SyrianSpock/stm32f4discovery_rosserial#1]
Hello,
Thanks a lot for sharing this project!
I would like to use my ST Nucleo with ROS and ChibiOS so I gave a try to your implementation.
Everything seems quite OK but on my Nucleo, the topics are present but the publishers do not publish the data regularly and create some `Lost sync with device, restarting...` issue on the `rosserial_python` node.
If I use only a subscriber (LED), it is OK, I can toggle the LED with `rostopic pub`.
If I use a Logic Analyzer, the STM32 does no publish the data regularly, only after a "restart" from the python node.
I know that the Nucleo use a serial port and not a real USB port, do you think that could be the issue?
Do you already faced that issue?
I know that you are not the support for rosserial but the issue seems related to ChibiOS more than rosserial and I am new to ChibiOS so I thought than maybe you have an idea.
I have tried both on Nucleo F401 and L476.
Thank you.

**Comment by romainreignier** [comment]
Actually, I have just noticed that you had the exact same issue before switching to BaseChannel. But for me, the issue remains.

**Comment by romainreignier** [comment]
And I have tested on a Nucleo 144 F429 with your code using the native USB port and I get the same sync errors :/
So if you have any ideas... :)

**Comment by SyrianSpock** [comment]
Hi, I'll look into this over the week-end.
I also have a Nucleo F429, so I can try to replicate your problem.

**Comment by romainreignier** [comment]
After some more testing, it appears that with only the ChibiOS HAL and not the RTOS part (osal/os-less), it works.
So I have an issue with the RT part, a thread must go to sleep... And I am new with ChibiOS RT.
